---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-oadp-operator
  namespace: openshift-adp
spec:
  installPlanApproval: Manual
  startingCSV: oadp-operator.v1.0.1

