---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-policies-a
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/danifernandezs/RHACM-OADP-Operator-via-GitOps.git
    targetRevision: main
    path: acm-governance/acm-policies-a/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
